CREATE TABLE PROJECT_EXTRA_TASK_HISTORY (
  ID_PROJECT_EXTRA_TASK_HISTORY SERIAL  NOT NULL ,
  ID_PROJECT INTEGER    ,
  ID_EXTRA_TASK INTEGER    ,
  UP_USER VARCHAR(50)    ,
  UP_DATE TIMESTAMP      ,
PRIMARY KEY(ID_PROJECT_EXTRA_TASK_HISTORY));




CREATE TABLE PROJECT_HISTORY (
  ID_PROJECT_HISTORY SERIAL  NOT NULL ,
  ID_PROJECT_STATE INTEGER    ,
  NAME VARCHAR(100)    ,
  REAL_UNITS INTEGER    ,
  UP_USER VARCHAR(50)    ,
  UP_DATE TIMESTAMP      ,
PRIMARY KEY(ID_PROJECT_HISTORY));




CREATE TABLE T_PROJECT_TYPES (
  ID_PROJECT_TYPE SERIAL  NOT NULL ,
  NAME VARCHAR(50)      ,
PRIMARY KEY(ID_PROJECT_TYPE));




CREATE TABLE T_PARAMETER_TYPES (
  ID_PARAMETER_TYPE SERIAL  NOT NULL ,
  NAME VARCHAR(50)      ,
PRIMARY KEY(ID_PARAMETER_TYPE));




CREATE TABLE TASK_PARAMETERS_HISTORY (
  ID_TASK_PARAMETERS_HISTORY SERIAL  NOT NULL ,
  ID_TASK INTEGER    ,
  ID_PARAMETER INTEGER    ,
  UP_USER VARCHAR(50)    ,
  UP_DATE TIMESTAMP      ,
PRIMARY KEY(ID_TASK_PARAMETERS_HISTORY));




CREATE TABLE TASK_HISTORY (
  ID_TASK_HISTORY SERIAL  NOT NULL ,
  ID_TASK INTEGER   NOT NULL ,
  ID_MODULE INTEGER    ,
  ID_SUBMODULE INTEGER    ,
  ID_FEATURE_TYPE INTEGER    ,
  REAL_UNITS INTEGER   NOT NULL ,
  NAME VARCHAR(50)   NOT NULL ,
  UP_USER VARCHAR(50)    ,
  UP_DATE TIMESTAMP      ,
PRIMARY KEY(ID_TASK_HISTORY));





CREATE TABLE PROJECT_STATES (
  ID_PROJECT_STATE SERIAL  NOT NULL ,
  NAME VARCHAR(50)      ,
PRIMARY KEY(ID_PROJECT_STATE));




CREATE TABLE T_ACTIVITIES (
  ID_ACTIVITY SERIAL  NOT NULL ,
  NAME VARCHAR(50)      ,
PRIMARY KEY(ID_ACTIVITY));




CREATE TABLE LANGUAGES (
  ID_LANGUAGE SERIAL  NOT NULL   ,
PRIMARY KEY(ID_LANGUAGE));




CREATE TABLE CLIENTS (
  ID_CLIENT SERIAL  NOT NULL ,
  NAME VARCHAR(50)      ,
PRIMARY KEY(ID_CLIENT));




CREATE TABLE ROLES (
  ID_ROLE SERIAL  NOT NULL ,
  ID_SUPER_ROLE INTEGER   NOT NULL ,
  ID_CLIENT INTEGER   NOT NULL ,
  NAME VARCHAR(50)      ,
PRIMARY KEY(ID_ROLE)    ,
  FOREIGN KEY(ID_CLIENT)
    REFERENCES CLIENTS(ID_CLIENT),
  FOREIGN KEY(ID_SUPER_ROLE)
    REFERENCES ROLES(ID_ROLE));


CREATE INDEX ROLES_FKIndex1 ON ROLES (ID_CLIENT);
CREATE INDEX ROLES_FKIndex2 ON ROLES (ID_SUPER_ROLE);


CREATE INDEX IFK_Rel_09_B ON ROLES (ID_CLIENT);
CREATE INDEX IFK_Rel_46 ON ROLES (ID_SUPER_ROLE);


CREATE TABLE GROUPS (
  ID_GROUP SERIAL  NOT NULL ,
  ID_CLIENT INTEGER   NOT NULL ,
  NAME VARCHAR(50)      ,
PRIMARY KEY(ID_GROUP)  ,
  FOREIGN KEY(ID_CLIENT)
    REFERENCES CLIENTS(ID_CLIENT));


CREATE INDEX GROUPS_FKIndex1 ON GROUPS (ID_CLIENT);


CREATE INDEX IFK_Rel_10_B ON GROUPS (ID_CLIENT);


CREATE TABLE PROJECT_TYPES (
  ID_PROJECT_TYPE SERIAL  NOT NULL ,
  ID_PROJECT_TYPE_V1 INTEGER  DEFAULT NULL  ,
  ID_CLIENT INTEGER   NOT NULL ,
  NAME VARCHAR(50)   NOT NULL ,
  VERSION INTEGER  DEFAULT 1 NOT NULL ,
  AVAILABLE CHAR  DEFAULT 'N' NOT NULL   ,
PRIMARY KEY(ID_PROJECT_TYPE)    ,
  FOREIGN KEY(ID_CLIENT)
    REFERENCES CLIENTS(ID_CLIENT),
  FOREIGN KEY(ID_PROJECT_TYPE_V1)
    REFERENCES PROJECT_TYPES(ID_PROJECT_TYPE));


CREATE INDEX PROJECT_TYPES_FKIndex1 ON PROJECT_TYPES (ID_CLIENT);
CREATE INDEX PROJECT_TYPES_FKIndex2 ON PROJECT_TYPES (ID_PROJECT_TYPE_V1);


CREATE INDEX IFK_Rel_21 ON PROJECT_TYPES (ID_CLIENT);
CREATE INDEX IFK_Rel_53 ON PROJECT_TYPES (ID_PROJECT_TYPE_V1);


CREATE TABLE USERS (
  ID_USER SERIAL  NOT NULL ,
  ID_CLIENT INTEGER   NOT NULL ,
  USERNAME VARCHAR(50)   NOT NULL ,
  PASSWORD_ENCODED VARCHAR(50)   NOT NULL ,
  NAME VARCHAR(50)   NOT NULL ,
  LASTNAME VARCHAR(50)    ,
  EMAIL VARCHAR(50)   NOT NULL   ,
PRIMARY KEY(ID_USER)  ,
  FOREIGN KEY(ID_CLIENT)
    REFERENCES CLIENTS(ID_CLIENT));


CREATE INDEX USERS_FKIndex1 ON USERS (ID_CLIENT);


CREATE INDEX IFK_Rel_08_B ON USERS (ID_CLIENT);


CREATE TABLE T_FEATURE_TYPES (
  ID_FEATURE_TYPE SERIAL  NOT NULL ,
  ID_ACTIVITY INTEGER   NOT NULL ,
  NAME VARCHAR(50)   NOT NULL ,
  ESTIMATED_UNITS INTEGER   NOT NULL   ,
PRIMARY KEY(ID_FEATURE_TYPE)  ,
  FOREIGN KEY(ID_ACTIVITY)
    REFERENCES T_ACTIVITIES(ID_ACTIVITY));


CREATE INDEX T_FEATURE_TYPES_FKIndex1 ON T_FEATURE_TYPES (ID_ACTIVITY);


CREATE INDEX IFK_Rel_48_B ON T_FEATURE_TYPES (ID_ACTIVITY);


CREATE TABLE PARAMETER_TYPES (
  ID_PARAMETER_TYPE SERIAL  NOT NULL ,
  ID_CLIENT INTEGER   NOT NULL ,
  NAME VARCHAR(50)      ,
PRIMARY KEY(ID_PARAMETER_TYPE)  ,
  FOREIGN KEY(ID_CLIENT)
    REFERENCES CLIENTS(ID_CLIENT));


CREATE INDEX PARAMETER_TYPES_FKIndex1 ON PARAMETER_TYPES (ID_CLIENT);


CREATE INDEX IFK_Rel_22 ON PARAMETER_TYPES (ID_CLIENT);


CREATE TABLE PARAMETERS (
  ID_PARAMETER SERIAL  NOT NULL ,
  ID_PARAMETER_TYPE INTEGER   NOT NULL ,
  MULTIPLIER FLOAT   NOT NULL ,
  MIN_VALUE INTEGER    ,
  MAX_VALUE INTEGER      ,
PRIMARY KEY(ID_PARAMETER)  ,
  FOREIGN KEY(ID_PARAMETER_TYPE)
    REFERENCES PARAMETER_TYPES(ID_PARAMETER_TYPE));


CREATE INDEX PARAMETERS_FKIndex1 ON PARAMETERS (ID_PARAMETER_TYPE);


CREATE INDEX IFK_Rel_24 ON PARAMETERS (ID_PARAMETER_TYPE);


CREATE TABLE MESSAGES (
  MESSAGE_KEY SERIAL  NOT NULL ,
  ID_LANGUAGE INTEGER   NOT NULL ,
  LOCALIZED_STRING VARCHAR(50)   NOT NULL   ,
PRIMARY KEY(MESSAGE_KEY, ID_LANGUAGE)  ,
  FOREIGN KEY(ID_LANGUAGE)
    REFERENCES LANGUAGES(ID_LANGUAGE));


CREATE INDEX MESSAGES_FKIndex1 ON MESSAGES (ID_LANGUAGE);


CREATE INDEX IFK_Rel_17 ON MESSAGES (ID_LANGUAGE);


CREATE TABLE ACTIVITIES (
  ID_ACTIVITY SERIAL  NOT NULL ,
  ID_CLIENT INTEGER   NOT NULL ,
  NAME VARCHAR(50)      ,
PRIMARY KEY(ID_ACTIVITY)  ,
  FOREIGN KEY(ID_CLIENT)
    REFERENCES CLIENTS(ID_CLIENT));


CREATE INDEX ACTIVITIES_FKIndex1 ON ACTIVITIES (ID_CLIENT);


CREATE INDEX IFK_Rel_32 ON ACTIVITIES (ID_CLIENT);


CREATE TABLE T_PARAMETERS (
  ID_PARAMETER SERIAL  NOT NULL ,
  ID_PARAMETER_TYPE INTEGER   NOT NULL ,
  MULTIPLIER FLOAT   NOT NULL ,
  MIN_VALUE INTEGER    ,
  MAX_VALUE INTEGER      ,
PRIMARY KEY(ID_PARAMETER)  ,
  FOREIGN KEY(ID_PARAMETER_TYPE)
    REFERENCES T_PARAMETER_TYPES(ID_PARAMETER_TYPE));


CREATE INDEX T_PARAMETERS_FKIndex1 ON T_PARAMETERS (ID_PARAMETER_TYPE);


CREATE INDEX IFK_Rel_47_B ON T_PARAMETERS (ID_PARAMETER_TYPE);


CREATE TABLE T_PROJECT_TYPE_ACTIVITIES (
  ID_PROJECT_TYPE INTEGER   NOT NULL ,
  ID_ACTIVITY INTEGER   NOT NULL ,
  PERCENTAGE FLOAT   NOT NULL   ,
PRIMARY KEY(ID_PROJECT_TYPE, ID_ACTIVITY)    ,
  FOREIGN KEY(ID_PROJECT_TYPE)
    REFERENCES T_PROJECT_TYPES(ID_PROJECT_TYPE),
  FOREIGN KEY(ID_ACTIVITY)
    REFERENCES T_ACTIVITIES(ID_ACTIVITY));


CREATE INDEX T_PROJECT_TYPES_has_T_ACTIVITIES_FKIndex1 ON T_PROJECT_TYPE_ACTIVITIES (ID_PROJECT_TYPE);
CREATE INDEX T_PROJECT_TYPES_has_T_ACTIVITIES_FKIndex2 ON T_PROJECT_TYPE_ACTIVITIES (ID_ACTIVITY);


CREATE INDEX IFK_Rel_49_B ON T_PROJECT_TYPE_ACTIVITIES (ID_PROJECT_TYPE);
CREATE INDEX IFK_Rel_50_B ON T_PROJECT_TYPE_ACTIVITIES (ID_ACTIVITY);


CREATE TABLE T_PROJECT_TYPE_FEATURE_TYPES (
  ID_PROJECT_TYPE INTEGER   NOT NULL ,
  ID_FEATURE_TYPE INTEGER   NOT NULL   ,
PRIMARY KEY(ID_PROJECT_TYPE, ID_FEATURE_TYPE)    ,
  FOREIGN KEY(ID_PROJECT_TYPE)
    REFERENCES T_PROJECT_TYPES(ID_PROJECT_TYPE),
  FOREIGN KEY(ID_FEATURE_TYPE)
    REFERENCES T_FEATURE_TYPES(ID_FEATURE_TYPE));


CREATE INDEX T_PROJECT_TYPES_has_T_FEATURE_TYPES_FKIndex1 ON T_PROJECT_TYPE_FEATURE_TYPES (ID_PROJECT_TYPE);
CREATE INDEX T_PROJECT_TYPES_has_T_FEATURE_TYPES_FKIndex2 ON T_PROJECT_TYPE_FEATURE_TYPES (ID_FEATURE_TYPE);


CREATE INDEX IFK_Rel_43 ON T_PROJECT_TYPE_FEATURE_TYPES (ID_PROJECT_TYPE);
CREATE INDEX IFK_Rel_44_B ON T_PROJECT_TYPE_FEATURE_TYPES (ID_FEATURE_TYPE);


CREATE TABLE T_PROJECT_TYPE_PARAMETER_TYPES (
  ID_PROJECT_TYPE INTEGER   NOT NULL ,
  ID_PARAMETER_TYPE INTEGER   NOT NULL   ,
PRIMARY KEY(ID_PROJECT_TYPE, ID_PARAMETER_TYPE)    ,
  FOREIGN KEY(ID_PROJECT_TYPE)
    REFERENCES T_PROJECT_TYPES(ID_PROJECT_TYPE),
  FOREIGN KEY(ID_PARAMETER_TYPE)
    REFERENCES T_PARAMETER_TYPES(ID_PARAMETER_TYPE));


CREATE INDEX T_PROJECT_TYPES_has_T_PARAMETER_TYPES_FKIndex1 ON T_PROJECT_TYPE_PARAMETER_TYPES (ID_PROJECT_TYPE);
CREATE INDEX T_PROJECT_TYPES_has_T_PARAMETER_TYPES_FKIndex2 ON T_PROJECT_TYPE_PARAMETER_TYPES (ID_PARAMETER_TYPE);


CREATE INDEX IFK_Rel_45 ON T_PROJECT_TYPE_PARAMETER_TYPES (ID_PROJECT_TYPE);
CREATE INDEX IFK_Rel_46_B ON T_PROJECT_TYPE_PARAMETER_TYPES (ID_PARAMETER_TYPE);


CREATE TABLE GROUPS_USERS (
  ID_GROUP INTEGER   NOT NULL ,
  ID_USER INTEGER   NOT NULL   ,
PRIMARY KEY(ID_GROUP, ID_USER)    ,
  FOREIGN KEY(ID_GROUP)
    REFERENCES GROUPS(ID_GROUP),
  FOREIGN KEY(ID_USER)
    REFERENCES USERS(ID_USER));


CREATE INDEX GROUPS_has_USERS_FKIndex1 ON GROUPS_USERS (ID_GROUP);
CREATE INDEX GROUPS_has_USERS_FKIndex2 ON GROUPS_USERS (ID_USER);


CREATE INDEX IFK_Rel_12 ON GROUPS_USERS (ID_GROUP);
CREATE INDEX IFK_Rel_13 ON GROUPS_USERS (ID_USER);


CREATE TABLE EXTRA_TASKS (
  ID_EXTRA_TASK SERIAL  NOT NULL ,
  ID_ACTIVITY INTEGER   NOT NULL ,
  ID_CLIENT INTEGER   NOT NULL ,
  NAME VARCHAR(50)   NOT NULL ,
  ESTIMATED_UNITS INTEGER   NOT NULL   ,
PRIMARY KEY(ID_EXTRA_TASK)    ,
  FOREIGN KEY(ID_CLIENT)
    REFERENCES CLIENTS(ID_CLIENT),
  FOREIGN KEY(ID_ACTIVITY)
    REFERENCES ACTIVITIES(ID_ACTIVITY));


CREATE INDEX EXTRA_TASKS_FKIndex1 ON EXTRA_TASKS (ID_CLIENT);
CREATE INDEX EXTRA_TASKS_FKIndex2 ON EXTRA_TASKS (ID_ACTIVITY);


CREATE INDEX IFK_Rel_47 ON EXTRA_TASKS (ID_CLIENT);
CREATE INDEX IFK_Rel_48 ON EXTRA_TASKS (ID_ACTIVITY);


CREATE TABLE FEATURE_TYPES (
  ID_FEATURE_TYPE SERIAL  NOT NULL ,
  ID_ACTIVITY INTEGER   NOT NULL ,
  ID_CLIENT INTEGER   NOT NULL ,
  NAME VARCHAR(50)   NOT NULL ,
  DESCRIPTION TEXT    ,
  ESTIMATED_UNITS INTEGER   NOT NULL   ,
PRIMARY KEY(ID_FEATURE_TYPE)    ,
  FOREIGN KEY(ID_CLIENT)
    REFERENCES CLIENTS(ID_CLIENT),
  FOREIGN KEY(ID_ACTIVITY)
    REFERENCES ACTIVITIES(ID_ACTIVITY));


CREATE INDEX FEATURE_TYPES_FKIndex1 ON FEATURE_TYPES (ID_CLIENT);
CREATE INDEX FEATURE_TYPES_FKIndex2 ON FEATURE_TYPES (ID_ACTIVITY);


CREATE INDEX IFK_Rel_23 ON FEATURE_TYPES (ID_CLIENT);
CREATE INDEX IFK_Rel_33 ON FEATURE_TYPES (ID_ACTIVITY);


CREATE TABLE GROUPS_ROLES (
  ID_GROUP INTEGER   NOT NULL ,
  ID_ROLE INTEGER   NOT NULL   ,
PRIMARY KEY(ID_GROUP, ID_ROLE)    ,
  FOREIGN KEY(ID_GROUP)
    REFERENCES GROUPS(ID_GROUP),
  FOREIGN KEY(ID_ROLE)
    REFERENCES ROLES(ID_ROLE));


CREATE INDEX GROUPS_has_ROLES_FKIndex1 ON GROUPS_ROLES (ID_GROUP);
CREATE INDEX GROUPS_has_ROLES_FKIndex2 ON GROUPS_ROLES (ID_ROLE);


CREATE INDEX IFK_Rel_08 ON GROUPS_ROLES (ID_GROUP);
CREATE INDEX IFK_Rel_09 ON GROUPS_ROLES (ID_ROLE);


CREATE TABLE PROJECT_TYPE_ACTIVITIES (
  ID_PROJECT_TYPE INTEGER   NOT NULL ,
  ID_ACTIVITY INTEGER   NOT NULL ,
  PERCENTAGE FLOAT      ,
PRIMARY KEY(ID_PROJECT_TYPE, ID_ACTIVITY)    ,
  FOREIGN KEY(ID_PROJECT_TYPE)
    REFERENCES PROJECT_TYPES(ID_PROJECT_TYPE),
  FOREIGN KEY(ID_ACTIVITY)
    REFERENCES ACTIVITIES(ID_ACTIVITY));


CREATE INDEX PROJECT_TYPES_has_ACTIVITIES_FKIndex1 ON PROJECT_TYPE_ACTIVITIES (ID_PROJECT_TYPE);
CREATE INDEX PROJECT_TYPES_has_ACTIVITIES_FKIndex2 ON PROJECT_TYPE_ACTIVITIES (ID_ACTIVITY);


CREATE INDEX IFK_Rel_36 ON PROJECT_TYPE_ACTIVITIES (ID_PROJECT_TYPE);
CREATE INDEX IFK_Rel_37 ON PROJECT_TYPE_ACTIVITIES (ID_ACTIVITY);


CREATE TABLE PROJECT_TYPE_PARAMETER_TYPES (
  ID_PROJECT_TYPE INTEGER   NOT NULL ,
  ID_PARAMETER_TYPE INTEGER   NOT NULL   ,
PRIMARY KEY(ID_PROJECT_TYPE, ID_PARAMETER_TYPE)    ,
  FOREIGN KEY(ID_PROJECT_TYPE)
    REFERENCES PROJECT_TYPES(ID_PROJECT_TYPE),
  FOREIGN KEY(ID_PARAMETER_TYPE)
    REFERENCES PARAMETER_TYPES(ID_PARAMETER_TYPE));


CREATE INDEX PROJECT_TYPES_has_PARAMETER_TYPES_FKIndex1 ON PROJECT_TYPE_PARAMETER_TYPES (ID_PROJECT_TYPE);
CREATE INDEX PROJECT_TYPES_has_PARAMETER_TYPES_FKIndex2 ON PROJECT_TYPE_PARAMETER_TYPES (ID_PARAMETER_TYPE);


CREATE INDEX IFK_Rel_28 ON PROJECT_TYPE_PARAMETER_TYPES (ID_PROJECT_TYPE);
CREATE INDEX IFK_Rel_29 ON PROJECT_TYPE_PARAMETER_TYPES (ID_PARAMETER_TYPE);


CREATE TABLE ROLES_USERS (
  ID_ROLE INTEGER   NOT NULL ,
  ID_USER INTEGER   NOT NULL   ,
PRIMARY KEY(ID_ROLE, ID_USER)    ,
  FOREIGN KEY(ID_ROLE)
    REFERENCES ROLES(ID_ROLE),
  FOREIGN KEY(ID_USER)
    REFERENCES USERS(ID_USER));


CREATE INDEX ROLES_has_USERS_FKIndex1 ON ROLES_USERS (ID_ROLE);
CREATE INDEX ROLES_has_USERS_FKIndex2 ON ROLES_USERS (ID_USER);


CREATE INDEX IFK_Rel_10 ON ROLES_USERS (ID_ROLE);
CREATE INDEX IFK_Rel_11 ON ROLES_USERS (ID_USER);


CREATE TABLE PROJECT_TYPE_EXTRA_TASKS (
  ID_PROJECT_TYPE INTEGER   NOT NULL ,
  ID_EXTRA_TASK INTEGER   NOT NULL   ,
PRIMARY KEY(ID_PROJECT_TYPE, ID_EXTRA_TASK)    ,
  FOREIGN KEY(ID_PROJECT_TYPE)
    REFERENCES PROJECT_TYPES(ID_PROJECT_TYPE),
  FOREIGN KEY(ID_EXTRA_TASK)
    REFERENCES EXTRA_TASKS(ID_EXTRA_TASK));


CREATE INDEX PROJECT_TYPES_has_EXTRA_TASKS_FKIndex1 ON PROJECT_TYPE_EXTRA_TASKS (ID_PROJECT_TYPE);
CREATE INDEX PROJECT_TYPES_has_EXTRA_TASKS_FKIndex2 ON PROJECT_TYPE_EXTRA_TASKS (ID_EXTRA_TASK);


CREATE INDEX IFK_Rel_49 ON PROJECT_TYPE_EXTRA_TASKS (ID_PROJECT_TYPE);
CREATE INDEX IFK_Rel_50 ON PROJECT_TYPE_EXTRA_TASKS (ID_EXTRA_TASK);


CREATE TABLE PROJECT_TYPE_FEATURE_TYPES (
  ID_PROJECT_TYPE INTEGER   NOT NULL ,
  ID_FEATURE_TYPE INTEGER   NOT NULL   ,
PRIMARY KEY(ID_PROJECT_TYPE, ID_FEATURE_TYPE)    ,
  FOREIGN KEY(ID_PROJECT_TYPE)
    REFERENCES PROJECT_TYPES(ID_PROJECT_TYPE),
  FOREIGN KEY(ID_FEATURE_TYPE)
    REFERENCES FEATURE_TYPES(ID_FEATURE_TYPE));


CREATE INDEX PROJECT_TYPES_has_FEATURE_TYPES_FKIndex1 ON PROJECT_TYPE_FEATURE_TYPES (ID_PROJECT_TYPE);
CREATE INDEX PROJECT_TYPES_has_FEATURE_TYPES_FKIndex2 ON PROJECT_TYPE_FEATURE_TYPES (ID_FEATURE_TYPE);


CREATE INDEX IFK_Rel_30 ON PROJECT_TYPE_FEATURE_TYPES (ID_PROJECT_TYPE);
CREATE INDEX IFK_Rel_31 ON PROJECT_TYPE_FEATURE_TYPES (ID_FEATURE_TYPE);


CREATE TABLE PROJECTS (
  ID_PROJECT SERIAL  NOT NULL ,
  ID_PROJECT_STATE INTEGER   NOT NULL ,
  ID_PRINCIPAL_ACTIVITY INTEGER   NOT NULL ,
  ID_PROJECT_TYPE INTEGER   NOT NULL ,
  ID_CLIENT INTEGER   NOT NULL ,
  NAME VARCHAR(50)   NOT NULL ,
  REAL_UNITS INTEGER      ,
PRIMARY KEY(ID_PROJECT)        ,
  FOREIGN KEY(ID_CLIENT)
    REFERENCES CLIENTS(ID_CLIENT),
  FOREIGN KEY(ID_PROJECT_TYPE)
    REFERENCES PROJECT_TYPES(ID_PROJECT_TYPE),
  FOREIGN KEY(ID_PRINCIPAL_ACTIVITY)
    REFERENCES ACTIVITIES(ID_ACTIVITY),
  FOREIGN KEY(ID_PROJECT_STATE)
    REFERENCES PROJECT_STATES(ID_PROJECT_STATE));


CREATE INDEX PROJECTS_FKIndex1 ON PROJECTS (ID_CLIENT);
CREATE INDEX PROJECTS_FKIndex2 ON PROJECTS (ID_PROJECT_TYPE);
CREATE INDEX PROJECTS_FKIndex3 ON PROJECTS (ID_PRINCIPAL_ACTIVITY);
CREATE INDEX PROJECTS_FKIndex4 ON PROJECTS (ID_PROJECT_STATE);



CREATE INDEX IFK_Rel_19 ON PROJECTS (ID_CLIENT);
CREATE INDEX IFK_Rel_20 ON PROJECTS (ID_PROJECT_TYPE);
CREATE INDEX IFK_Rel_35 ON PROJECTS (ID_PRINCIPAL_ACTIVITY);
CREATE INDEX IFK_Rel_40 ON PROJECTS (ID_PROJECT_STATE);


CREATE TABLE SUBSYSTEMS (
  ID_SUBSYSTEM SERIAL  NOT NULL ,
  ID_PROJECT INTEGER   NOT NULL ,
  NAME VARCHAR(50)   NOT NULL   ,
PRIMARY KEY(ID_SUBSYSTEM)  ,
  FOREIGN KEY(ID_PROJECT)
    REFERENCES PROJECTS(ID_PROJECT));


CREATE INDEX SUBSYSTEMS_FKIndex1 ON SUBSYSTEMS (ID_PROJECT);


CREATE INDEX IFK_Rel_12_B ON SUBSYSTEMS (ID_PROJECT);


CREATE TABLE MODULES (
  ID_MODULE SERIAL  NOT NULL ,
  ID_SUBSYSTEM INTEGER   NOT NULL ,
  ID_PROJECT INTEGER   NOT NULL ,
  NAME VARCHAR(50)      ,
PRIMARY KEY(ID_MODULE)    ,
  FOREIGN KEY(ID_PROJECT)
    REFERENCES PROJECTS(ID_PROJECT),
  FOREIGN KEY(ID_SUBSYSTEM)
    REFERENCES SUBSYSTEMS(ID_SUBSYSTEM));


CREATE INDEX MODULES_FKIndex1 ON MODULES (ID_PROJECT);
CREATE INDEX MODULES_FKIndex2 ON MODULES (ID_SUBSYSTEM);


CREATE INDEX IFK_Rel_13_B ON MODULES (ID_PROJECT);
CREATE INDEX IFK_Rel_17_B ON MODULES (ID_SUBSYSTEM);


CREATE TABLE PROJECT_EXTRA_TASKS (
  ID_PROJECT INTEGER   NOT NULL ,
  ID_EXTRA_TASK INTEGER   NOT NULL ,
  MULTIPLIER FLOAT  DEFAULT 1 NOT NULL ,
  JUSTIFICATION TEXT      ,
PRIMARY KEY(ID_PROJECT, ID_EXTRA_TASK)    ,
  FOREIGN KEY(ID_PROJECT)
    REFERENCES PROJECTS(ID_PROJECT),
  FOREIGN KEY(ID_EXTRA_TASK)
    REFERENCES EXTRA_TASKS(ID_EXTRA_TASK));


CREATE INDEX PROJECTS_has_EXTRA_TASKS_FKIndex1 ON PROJECT_EXTRA_TASKS (ID_PROJECT);
CREATE INDEX PROJECTS_has_EXTRA_TASKS_FKIndex2 ON PROJECT_EXTRA_TASKS (ID_EXTRA_TASK);




CREATE INDEX IFK_Rel_51 ON PROJECT_EXTRA_TASKS (ID_PROJECT);
CREATE INDEX IFK_Rel_52 ON PROJECT_EXTRA_TASKS (ID_EXTRA_TASK);


CREATE TABLE SUBMODULES (
  ID_SUBMODULE SERIAL  NOT NULL ,
  ID_MODULE INTEGER   NOT NULL ,
  ID_PROJECT INTEGER   NOT NULL ,
  NAME VARCHAR(50)   NOT NULL   ,
PRIMARY KEY(ID_SUBMODULE)    ,
  FOREIGN KEY(ID_PROJECT)
    REFERENCES PROJECTS(ID_PROJECT),
  FOREIGN KEY(ID_MODULE)
    REFERENCES MODULES(ID_MODULE));


CREATE INDEX SUBMODULES_FKIndex1 ON SUBMODULES (ID_PROJECT);
CREATE INDEX SUBMODULES_FKIndex2 ON SUBMODULES (ID_MODULE);


CREATE INDEX IFK_Rel_14 ON SUBMODULES (ID_PROJECT);
CREATE INDEX IFK_Rel_18 ON SUBMODULES (ID_MODULE);


CREATE TABLE TASKS (
  ID_TASK SERIAL  NOT NULL ,
  ID_FEATURE_TYPE INTEGER   NOT NULL ,
  ID_SUBMODULE INTEGER    ,
  ID_MODULE INTEGER    ,
  ID_PROJECT INTEGER   NOT NULL ,
  NAME VARCHAR(50)   NOT NULL ,
  REAL_UNITS INTEGER   NOT NULL   ,
PRIMARY KEY(ID_TASK)        ,
  FOREIGN KEY(ID_PROJECT)
    REFERENCES PROJECTS(ID_PROJECT),
  FOREIGN KEY(ID_MODULE)
    REFERENCES MODULES(ID_MODULE),
  FOREIGN KEY(ID_SUBMODULE)
    REFERENCES SUBMODULES(ID_SUBMODULE),
  FOREIGN KEY(ID_FEATURE_TYPE)
    REFERENCES FEATURE_TYPES(ID_FEATURE_TYPE));


CREATE INDEX TASKS_FKIndex1 ON TASKS (ID_PROJECT);
CREATE INDEX TASKS_FKIndex2 ON TASKS (ID_MODULE);
CREATE INDEX TASKS_FKIndex3 ON TASKS (ID_SUBMODULE);
CREATE INDEX TASKS_FKIndex4 ON TASKS (ID_FEATURE_TYPE);



CREATE INDEX IFK_Rel_11_B ON TASKS (ID_PROJECT);
CREATE INDEX IFK_Rel_15 ON TASKS (ID_MODULE);
CREATE INDEX IFK_Rel_16 ON TASKS (ID_SUBMODULE);
CREATE INDEX IFK_Rel_25 ON TASKS (ID_FEATURE_TYPE);


CREATE TABLE TASK_PARAMETERS (
  ID_TASK INTEGER   NOT NULL ,
  ID_PARAMETER INTEGER   NOT NULL   ,
PRIMARY KEY(ID_TASK, ID_PARAMETER)    ,
  FOREIGN KEY(ID_TASK)
    REFERENCES TASKS(ID_TASK),
  FOREIGN KEY(ID_PARAMETER)
    REFERENCES PARAMETERS(ID_PARAMETER));


CREATE INDEX TASKS_has_PARAMETERS_FKIndex1 ON TASK_PARAMETERS (ID_TASK);
CREATE INDEX TASKS_has_PARAMETERS_FKIndex2 ON TASK_PARAMETERS (ID_PARAMETER);


CREATE INDEX IFK_Rel_26 ON TASK_PARAMETERS (ID_TASK);
CREATE INDEX IFK_Rel_27 ON TASK_PARAMETERS (ID_PARAMETER);



