package com.devgear.codesizer.model;

// Generated 24-oct-2011 0:54:57 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Activity generated by hbm2java
 */
@Entity
@Table(name = "activities", schema = "public")
public class Activity implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idActivity;
	private Client client;
	private String name;
	private Set<ProjectTypeActivities> projectTypeActivitieses = new HashSet<ProjectTypeActivities>(
			0);
	private Set<Project> projects = new HashSet<Project>(0);
	private Set<FeatureType> featureTypes = new HashSet<FeatureType>(0);
	private Set<ExtraTask> extraTasks = new HashSet<ExtraTask>(0);

	public Activity() {
	}

	public Activity(int idActivity, Client client) {
		this.idActivity = idActivity;
		this.client = client;
	}

	public Activity(int idActivity, Client client, String name,
			Set<ProjectTypeActivities> projectTypeActivitieses,
			Set<Project> projects, Set<FeatureType> featureTypes,
			Set<ExtraTask> extraTasks) {
		this.idActivity = idActivity;
		this.client = client;
		this.name = name;
		this.projectTypeActivitieses = projectTypeActivitieses;
		this.projects = projects;
		this.featureTypes = featureTypes;
		this.extraTasks = extraTasks;
	}

	@Id
	@Column(name = "id_activity", unique = true, nullable = false)
	public int getIdActivity() {
		return this.idActivity;
	}

	public void setIdActivity(int idActivity) {
		this.idActivity = idActivity;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_client", nullable = false)
	public Client getClient() {
		return this.client;
	}

	public void setClient(Client client) {
		this.client = client;
	}

	@Column(name = "name", length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "activity")
	public Set<ProjectTypeActivities> getProjectTypeActivitieses() {
		return this.projectTypeActivitieses;
	}

	public void setProjectTypeActivitieses(
			Set<ProjectTypeActivities> projectTypeActivitieses) {
		this.projectTypeActivitieses = projectTypeActivitieses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "activity")
	public Set<Project> getProjects() {
		return this.projects;
	}

	public void setProjects(Set<Project> projects) {
		this.projects = projects;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "activity")
	public Set<FeatureType> getFeatureTypes() {
		return this.featureTypes;
	}

	public void setFeatureTypes(Set<FeatureType> featureTypes) {
		this.featureTypes = featureTypes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "activity")
	public Set<ExtraTask> getExtraTasks() {
		return this.extraTasks;
	}

	public void setExtraTasks(Set<ExtraTask> extraTasks) {
		this.extraTasks = extraTasks;
	}

}
