package com.devgear.codesizer.model;

// Generated 24-oct-2011 0:54:57 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ProjectExtraTaskHistory generated by hbm2java
 */
@Entity
@Table(name = "project_extra_task_history", schema = "public")
public class ProjectExtraTaskHistory implements java.io.Serializable {

	private int idProjectExtraTaskHistory;
	private Integer idProject;
	private Integer idExtraTask;
	private String upUser;
	private Date upDate;

	public ProjectExtraTaskHistory() {
	}

	public ProjectExtraTaskHistory(int idProjectExtraTaskHistory) {
		this.idProjectExtraTaskHistory = idProjectExtraTaskHistory;
	}

	public ProjectExtraTaskHistory(int idProjectExtraTaskHistory,
			Integer idProject, Integer idExtraTask, String upUser, Date upDate) {
		this.idProjectExtraTaskHistory = idProjectExtraTaskHistory;
		this.idProject = idProject;
		this.idExtraTask = idExtraTask;
		this.upUser = upUser;
		this.upDate = upDate;
	}

	@Id
	@Column(name = "id_project_extra_task_history", unique = true, nullable = false)
	public int getIdProjectExtraTaskHistory() {
		return this.idProjectExtraTaskHistory;
	}

	public void setIdProjectExtraTaskHistory(int idProjectExtraTaskHistory) {
		this.idProjectExtraTaskHistory = idProjectExtraTaskHistory;
	}

	@Column(name = "id_project")
	public Integer getIdProject() {
		return this.idProject;
	}

	public void setIdProject(Integer idProject) {
		this.idProject = idProject;
	}

	@Column(name = "id_extra_task")
	public Integer getIdExtraTask() {
		return this.idExtraTask;
	}

	public void setIdExtraTask(Integer idExtraTask) {
		this.idExtraTask = idExtraTask;
	}

	@Column(name = "up_user", length = 50)
	public String getUpUser() {
		return this.upUser;
	}

	public void setUpUser(String upUser) {
		this.upUser = upUser;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "up_date", length = 29)
	public Date getUpDate() {
		return this.upDate;
	}

	public void setUpDate(Date upDate) {
		this.upDate = upDate;
	}

}
