package com.devgear.codesizer.model;

// Generated 24-oct-2011 0:54:57 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ProjectHistory generated by hbm2java
 */
@Entity
@Table(name = "project_history", schema = "public")
public class ProjectHistory implements java.io.Serializable {

	private int idProjectHistory;
	private Integer idProjectState;
	private String name;
	private Integer realUnits;
	private String upUser;
	private Date upDate;

	public ProjectHistory() {
	}

	public ProjectHistory(int idProjectHistory) {
		this.idProjectHistory = idProjectHistory;
	}

	public ProjectHistory(int idProjectHistory, Integer idProjectState,
			String name, Integer realUnits, String upUser, Date upDate) {
		this.idProjectHistory = idProjectHistory;
		this.idProjectState = idProjectState;
		this.name = name;
		this.realUnits = realUnits;
		this.upUser = upUser;
		this.upDate = upDate;
	}

	@Id
	@Column(name = "id_project_history", unique = true, nullable = false)
	public int getIdProjectHistory() {
		return this.idProjectHistory;
	}

	public void setIdProjectHistory(int idProjectHistory) {
		this.idProjectHistory = idProjectHistory;
	}

	@Column(name = "id_project_state")
	public Integer getIdProjectState() {
		return this.idProjectState;
	}

	public void setIdProjectState(Integer idProjectState) {
		this.idProjectState = idProjectState;
	}

	@Column(name = "name", length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "real_units")
	public Integer getRealUnits() {
		return this.realUnits;
	}

	public void setRealUnits(Integer realUnits) {
		this.realUnits = realUnits;
	}

	@Column(name = "up_user", length = 50)
	public String getUpUser() {
		return this.upUser;
	}

	public void setUpUser(String upUser) {
		this.upUser = upUser;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "up_date", length = 29)
	public Date getUpDate() {
		return this.upDate;
	}

	public void setUpDate(Date upDate) {
		this.upDate = upDate;
	}

}
