package com.devgear.codesizer.model;

// Generated 24-oct-2011 0:54:57 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ProjectTypeActivities generated by hbm2java
 */
@Entity
@Table(name = "project_type_activities", schema = "public")
public class ProjectTypeActivities implements java.io.Serializable {

	private ProjectTypeActivitiesId id;
	private Activity activity;
	private ProjectType projectType;
	private Double percentage;

	public ProjectTypeActivities() {
	}

	public ProjectTypeActivities(ProjectTypeActivitiesId id, Activity activity,
			ProjectType projectType) {
		this.id = id;
		this.activity = activity;
		this.projectType = projectType;
	}

	public ProjectTypeActivities(ProjectTypeActivitiesId id, Activity activity,
			ProjectType projectType, Double percentage) {
		this.id = id;
		this.activity = activity;
		this.projectType = projectType;
		this.percentage = percentage;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idActivity", column = @Column(name = "id_activity", nullable = false)),
			@AttributeOverride(name = "idProjectType", column = @Column(name = "id_project_type", nullable = false)) })
	public ProjectTypeActivitiesId getId() {
		return this.id;
	}

	public void setId(ProjectTypeActivitiesId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_activity", nullable = false, insertable = false, updatable = false)
	public Activity getActivity() {
		return this.activity;
	}

	public void setActivity(Activity activity) {
		this.activity = activity;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_project_type", nullable = false, insertable = false, updatable = false)
	public ProjectType getProjectType() {
		return this.projectType;
	}

	public void setProjectType(ProjectType projectType) {
		this.projectType = projectType;
	}

	@Column(name = "percentage", precision = 17, scale = 17)
	public Double getPercentage() {
		return this.percentage;
	}

	public void setPercentage(Double percentage) {
		this.percentage = percentage;
	}

}
