package com.devgear.codesizer.model;

// Generated 24-oct-2011 0:54:57 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TemplateProjectTypeFeatureType generated by hbm2java
 */
@Entity
@Table(name = "t_project_type_feature_types", schema = "public")
public class TemplateProjectTypeFeatureType implements java.io.Serializable {

	private TemplateProjectTypeFeatureTypeId id;
	private TemplateProjectType templateProjectType;
	private TemplateFeatureType templateFeatureType;
	private Integer estimatedUnits;

	public TemplateProjectTypeFeatureType() {
	}

	public TemplateProjectTypeFeatureType(TemplateProjectTypeFeatureTypeId id,
			TemplateProjectType templateProjectType,
			TemplateFeatureType templateFeatureType) {
		this.id = id;
		this.templateProjectType = templateProjectType;
		this.templateFeatureType = templateFeatureType;
	}

	public TemplateProjectTypeFeatureType(TemplateProjectTypeFeatureTypeId id,
			TemplateProjectType templateProjectType,
			TemplateFeatureType templateFeatureType, Integer estimatedUnits) {
		this.id = id;
		this.templateProjectType = templateProjectType;
		this.templateFeatureType = templateFeatureType;
		this.estimatedUnits = estimatedUnits;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idProjectType", column = @Column(name = "id_project_type", nullable = false)),
			@AttributeOverride(name = "idFeatureType", column = @Column(name = "id_feature_type", nullable = false)) })
	public TemplateProjectTypeFeatureTypeId getId() {
		return this.id;
	}

	public void setId(TemplateProjectTypeFeatureTypeId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_project_type", nullable = false, insertable = false, updatable = false)
	public TemplateProjectType getTemplateProjectType() {
		return this.templateProjectType;
	}

	public void setTemplateProjectType(TemplateProjectType templateProjectType) {
		this.templateProjectType = templateProjectType;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_feature_type", nullable = false, insertable = false, updatable = false)
	public TemplateFeatureType getTemplateFeatureType() {
		return this.templateFeatureType;
	}

	public void setTemplateFeatureType(TemplateFeatureType templateFeatureType) {
		this.templateFeatureType = templateFeatureType;
	}

	@Column(name = "estimated_units")
	public Integer getEstimatedUnits() {
		return this.estimatedUnits;
	}

	public void setEstimatedUnits(Integer estimatedUnits) {
		this.estimatedUnits = estimatedUnits;
	}

}
