package com.devgear.codesizer.model;

// Generated 24-oct-2011 0:54:57 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TemplateParameter generated by hbm2java
 */
@Entity
@Table(name = "t_parameters", schema = "public")
public class TemplateParameter implements java.io.Serializable {

	private int idParameter;
	private TemplateParameterType templateParameterType;
	private double multiplier;

	public TemplateParameter() {
	}

	public TemplateParameter(int idParameter,
			TemplateParameterType templateParameterType, double multiplier) {
		this.idParameter = idParameter;
		this.templateParameterType = templateParameterType;
		this.multiplier = multiplier;
	}

	@Id
	@Column(name = "id_parameter", unique = true, nullable = false)
	public int getIdParameter() {
		return this.idParameter;
	}

	public void setIdParameter(int idParameter) {
		this.idParameter = idParameter;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_parameter_type", nullable = false)
	public TemplateParameterType getTemplateParameterType() {
		return this.templateParameterType;
	}

	public void setTemplateParameterType(
			TemplateParameterType templateParameterType) {
		this.templateParameterType = templateParameterType;
	}

	@Column(name = "multiplier", nullable = false, precision = 17, scale = 17)
	public double getMultiplier() {
		return this.multiplier;
	}

	public void setMultiplier(double multiplier) {
		this.multiplier = multiplier;
	}

}
