package com.devgear.codesizer.model;

// Generated 24-oct-2011 0:54:57 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TemplateActivity generated by hbm2java
 */
@Entity
@Table(name = "t_activities", schema = "public")
public class TemplateActivity implements java.io.Serializable {

	private int idActivity;
	private String name;
	private Set<TemplateProjectTypeActivity> templateProjectTypeActivities = new HashSet<TemplateProjectTypeActivity>(
			0);
	private Set<TemplateFeatureType> templateFeatureTypes = new HashSet<TemplateFeatureType>(
			0);

	public TemplateActivity() {
	}

	public TemplateActivity(int idActivity) {
		this.idActivity = idActivity;
	}

	public TemplateActivity(int idActivity, String name,
			Set<TemplateProjectTypeActivity> templateProjectTypeActivities,
			Set<TemplateFeatureType> templateFeatureTypes) {
		this.idActivity = idActivity;
		this.name = name;
		this.templateProjectTypeActivities = templateProjectTypeActivities;
		this.templateFeatureTypes = templateFeatureTypes;
	}

	@Id
	@Column(name = "id_activity", unique = true, nullable = false)
	public int getIdActivity() {
		return this.idActivity;
	}

	public void setIdActivity(int idActivity) {
		this.idActivity = idActivity;
	}

	@Column(name = "name", length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "templateActivity")
	public Set<TemplateProjectTypeActivity> getTemplateProjectTypeActivities() {
		return this.templateProjectTypeActivities;
	}

	public void setTemplateProjectTypeActivities(
			Set<TemplateProjectTypeActivity> templateProjectTypeActivities) {
		this.templateProjectTypeActivities = templateProjectTypeActivities;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "templateActivity")
	public Set<TemplateFeatureType> getTemplateFeatureTypes() {
		return this.templateFeatureTypes;
	}

	public void setTemplateFeatureTypes(
			Set<TemplateFeatureType> templateFeatureTypes) {
		this.templateFeatureTypes = templateFeatureTypes;
	}

}
