package com.devgear.codesizer.model;

// Generated 24-oct-2011 0:54:57 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Client generated by hbm2java
 */
@Entity
@Table(name = "clients", schema = "public")
public class Client implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idClient;
	private String name;
	private Set<Role> roles = new HashSet<Role>(0);
	private Set<User> users = new HashSet<User>(0);
	private Set<Group> groups = new HashSet<Group>(0);
	private Set<ExtraTask> extraTasks = new HashSet<ExtraTask>(0);
	private Set<Activity> activities = new HashSet<Activity>(0);
	private Set<ProjectType> projectTypes = new HashSet<ProjectType>(0);
	private Set<ParameterType> parameterTypes = new HashSet<ParameterType>(0);
	private Set<Project> projects = new HashSet<Project>(0);
	private Set<FeatureType> featureTypes = new HashSet<FeatureType>(0);

	public Client() {
	}

	public Client(int idClient) {
		this.idClient = idClient;
	}

	public Client(int idClient, String name, Set<Role> roles, Set<User> users,
			Set<Group> groups, Set<ExtraTask> extraTasks,
			Set<Activity> activities, Set<ProjectType> projectTypes,
			Set<ParameterType> parameterTypes, Set<Project> projects,
			Set<FeatureType> featureTypes) {
		this.idClient = idClient;
		this.name = name;
		this.roles = roles;
		this.users = users;
		this.groups = groups;
		this.extraTasks = extraTasks;
		this.activities = activities;
		this.projectTypes = projectTypes;
		this.parameterTypes = parameterTypes;
		this.projects = projects;
		this.featureTypes = featureTypes;
	}

	@Id
	@Column(name = "id_client", unique = true, nullable = false)
	public int getIdClient() {
		return this.idClient;
	}

	public void setIdClient(int idClient) {
		this.idClient = idClient;
	}

	@Column(name = "name", length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "client")
	public Set<Role> getRoles() {
		return this.roles;
	}

	public void setRoles(Set<Role> roles) {
		this.roles = roles;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "client")
	public Set<User> getUsers() {
		return this.users;
	}

	public void setUsers(Set<User> users) {
		this.users = users;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "client")
	public Set<Group> getGroups() {
		return this.groups;
	}

	public void setGroups(Set<Group> groups) {
		this.groups = groups;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "client")
	public Set<ExtraTask> getExtraTasks() {
		return this.extraTasks;
	}

	public void setExtraTasks(Set<ExtraTask> extraTasks) {
		this.extraTasks = extraTasks;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "client")
	public Set<Activity> getActivities() {
		return this.activities;
	}

	public void setActivities(Set<Activity> activities) {
		this.activities = activities;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "client")
	public Set<ProjectType> getProjectTypes() {
		return this.projectTypes;
	}

	public void setProjectTypes(Set<ProjectType> projectTypes) {
		this.projectTypes = projectTypes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "client")
	public Set<ParameterType> getParameterTypes() {
		return this.parameterTypes;
	}

	public void setParameterTypes(Set<ParameterType> parameterTypes) {
		this.parameterTypes = parameterTypes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "client")
	public Set<Project> getProjects() {
		return this.projects;
	}

	public void setProjects(Set<Project> projects) {
		this.projects = projects;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "client")
	public Set<FeatureType> getFeatureTypes() {
		return this.featureTypes;
	}

	public void setFeatureTypes(Set<FeatureType> featureTypes) {
		this.featureTypes = featureTypes;
	}

}
