package com.devgear.codesizer.model;

// Generated 24-oct-2011 0:54:57 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * FeatureType generated by hbm2java
 */
@Entity
@Table(name = "feature_types", schema = "public")
public class FeatureType implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idFeatureType;
	private Activity activity;
	private Client client;
	private String name;
	private String description;
	private Set<Task> tasks = new HashSet<Task>(0);
	private Set<ProjectTypeFeatureTypes> projectTypeFeatureTypeses = new HashSet<ProjectTypeFeatureTypes>(
			0);

	public FeatureType() {
	}

	public FeatureType(int idFeatureType, Activity activity, Client client,
			String name) {
		this.idFeatureType = idFeatureType;
		this.activity = activity;
		this.client = client;
		this.name = name;
	}

	public FeatureType(int idFeatureType, Activity activity, Client client,
			String name, String description, Set<Task> tasks,
			Set<ProjectTypeFeatureTypes> projectTypeFeatureTypeses) {
		this.idFeatureType = idFeatureType;
		this.activity = activity;
		this.client = client;
		this.name = name;
		this.description = description;
		this.tasks = tasks;
		this.projectTypeFeatureTypeses = projectTypeFeatureTypeses;
	}

	@Id
	@Column(name = "id_feature_type", unique = true, nullable = false)
	public int getIdFeatureType() {
		return this.idFeatureType;
	}

	public void setIdFeatureType(int idFeatureType) {
		this.idFeatureType = idFeatureType;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_activity", nullable = false)
	public Activity getActivity() {
		return this.activity;
	}

	public void setActivity(Activity activity) {
		this.activity = activity;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_client", nullable = false)
	public Client getClient() {
		return this.client;
	}

	public void setClient(Client client) {
		this.client = client;
	}

	@Column(name = "name", nullable = false, length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "featureType")
	public Set<Task> getTasks() {
		return this.tasks;
	}

	public void setTasks(Set<Task> tasks) {
		this.tasks = tasks;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "featureType")
	public Set<ProjectTypeFeatureTypes> getProjectTypeFeatureTypeses() {
		return this.projectTypeFeatureTypeses;
	}

	public void setProjectTypeFeatureTypeses(
			Set<ProjectTypeFeatureTypes> projectTypeFeatureTypeses) {
		this.projectTypeFeatureTypeses = projectTypeFeatureTypeses;
	}

}
