package com.devgear.codesizer.model;

// Generated 24-oct-2011 0:54:57 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Language generated by hbm2java
 */
@Entity
@Table(name = "languages", schema = "public")
public class Language implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idLanguage;
	private Set<Message> messages = new HashSet<Message>(0);

	public Language() {
	}

	public Language(int idLanguage) {
		this.idLanguage = idLanguage;
	}

	public Language(int idLanguage, Set<Message> messages) {
		this.idLanguage = idLanguage;
		this.messages = messages;
	}

	@Id
	@Column(name = "id_language", unique = true, nullable = false)
	public int getIdLanguage() {
		return this.idLanguage;
	}

	public void setIdLanguage(int idLanguage) {
		this.idLanguage = idLanguage;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "language")
	public Set<Message> getMessages() {
		return this.messages;
	}

	public void setMessages(Set<Message> messages) {
		this.messages = messages;
	}

}
