package com.devgear.codesizer.model;

// Generated 24-oct-2011 0:54:57 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MessageId generated by hbm2java
 */
@Embeddable
public class MessageId implements java.io.Serializable {

	private int messageKey;
	private int idLanguage;

	public MessageId() {
	}

	public MessageId(int messageKey, int idLanguage) {
		this.messageKey = messageKey;
		this.idLanguage = idLanguage;
	}

	@Column(name = "message_key", nullable = false)
	public int getMessageKey() {
		return this.messageKey;
	}

	public void setMessageKey(int messageKey) {
		this.messageKey = messageKey;
	}

	@Column(name = "id_language", nullable = false)
	public int getIdLanguage() {
		return this.idLanguage;
	}

	public void setIdLanguage(int idLanguage) {
		this.idLanguage = idLanguage;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MessageId))
			return false;
		MessageId castOther = (MessageId) other;

		return (this.getMessageKey() == castOther.getMessageKey())
				&& (this.getIdLanguage() == castOther.getIdLanguage());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getMessageKey();
		result = 37 * result + this.getIdLanguage();
		return result;
	}

}
