package com.devgear.codesizer.model;

// Generated 24-oct-2011 0:54:57 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Module generated by hbm2java
 */
@Entity
@Table(name = "modules", schema = "public")
public class Module implements java.io.Serializable {

	private int idModule;
	private Project project;
	private Subsystems subsystems;
	private String name;
	private Set<Task> tasks = new HashSet<Task>(0);
	private Set<Submodule> submodules = new HashSet<Submodule>(0);

	public Module() {
	}

	public Module(int idModule, Project project, Subsystems subsystems) {
		this.idModule = idModule;
		this.project = project;
		this.subsystems = subsystems;
	}

	public Module(int idModule, Project project, Subsystems subsystems,
			String name, Set<Task> tasks, Set<Submodule> submodules) {
		this.idModule = idModule;
		this.project = project;
		this.subsystems = subsystems;
		this.name = name;
		this.tasks = tasks;
		this.submodules = submodules;
	}

	@Id
	@Column(name = "id_module", unique = true, nullable = false)
	public int getIdModule() {
		return this.idModule;
	}

	public void setIdModule(int idModule) {
		this.idModule = idModule;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_project", nullable = false)
	public Project getProject() {
		return this.project;
	}

	public void setProject(Project project) {
		this.project = project;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_subsystem", nullable = false)
	public Subsystems getSubsystems() {
		return this.subsystems;
	}

	public void setSubsystems(Subsystems subsystems) {
		this.subsystems = subsystems;
	}

	@Column(name = "name", length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "module")
	public Set<Task> getTasks() {
		return this.tasks;
	}

	public void setTasks(Set<Task> tasks) {
		this.tasks = tasks;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "module")
	public Set<Submodule> getSubmodules() {
		return this.submodules;
	}

	public void setSubmodules(Set<Submodule> submodules) {
		this.submodules = submodules;
	}

}
