package com.devgear.codesizer.model;

// Generated 24-oct-2011 0:54:57 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ProjectTypeFeatureTypesId generated by hbm2java
 */
@Embeddable
public class ProjectTypeFeatureTypesId implements java.io.Serializable {

	private int idProjectType;
	private int idFeatureType;

	public ProjectTypeFeatureTypesId() {
	}

	public ProjectTypeFeatureTypesId(int idProjectType, int idFeatureType) {
		this.idProjectType = idProjectType;
		this.idFeatureType = idFeatureType;
	}

	@Column(name = "id_project_type", nullable = false)
	public int getIdProjectType() {
		return this.idProjectType;
	}

	public void setIdProjectType(int idProjectType) {
		this.idProjectType = idProjectType;
	}

	@Column(name = "id_feature_type", nullable = false)
	public int getIdFeatureType() {
		return this.idFeatureType;
	}

	public void setIdFeatureType(int idFeatureType) {
		this.idFeatureType = idFeatureType;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ProjectTypeFeatureTypesId))
			return false;
		ProjectTypeFeatureTypesId castOther = (ProjectTypeFeatureTypesId) other;

		return (this.getIdProjectType() == castOther.getIdProjectType())
				&& (this.getIdFeatureType() == castOther.getIdFeatureType());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdProjectType();
		result = 37 * result + this.getIdFeatureType();
		return result;
	}

}
