package com.devgear.codesizer.model;

// Generated 24-oct-2011 0:54:57 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ProjectStates generated by hbm2java
 */
@Entity
@Table(name = "project_states", schema = "public")
public class ProjectStates implements java.io.Serializable {

	private int idProjectState;
	private String name;
	private Set<Project> projects = new HashSet<Project>(0);

	public ProjectStates() {
	}

	public ProjectStates(int idProjectState) {
		this.idProjectState = idProjectState;
	}

	public ProjectStates(int idProjectState, String name, Set<Project> projects) {
		this.idProjectState = idProjectState;
		this.name = name;
		this.projects = projects;
	}

	@Id
	@Column(name = "id_project_state", unique = true, nullable = false)
	public int getIdProjectState() {
		return this.idProjectState;
	}

	public void setIdProjectState(int idProjectState) {
		this.idProjectState = idProjectState;
	}

	@Column(name = "name", length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "projectStates")
	public Set<Project> getProjects() {
		return this.projects;
	}

	public void setProjects(Set<Project> projects) {
		this.projects = projects;
	}

}
