package com.devgear.codesizer.model;

// Generated 24-oct-2011 0:54:57 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Task generated by hbm2java
 */
@Entity
@Table(name = "tasks", schema = "public")
public class Task implements java.io.Serializable {

	private int idTask;
	private Project project;
	private Module module;
	private Submodule submodule;
	private FeatureType featureType;
	private String name;
	private int realUnits;
	private Set<Parameter> parameters = new HashSet<Parameter>(0);

	public Task() {
	}

	public Task(int idTask, Project project, FeatureType featureType,
			String name, int realUnits) {
		this.idTask = idTask;
		this.project = project;
		this.featureType = featureType;
		this.name = name;
		this.realUnits = realUnits;
	}

	public Task(int idTask, Project project, Module module,
			Submodule submodule, FeatureType featureType, String name,
			int realUnits, Set<Parameter> parameters) {
		this.idTask = idTask;
		this.project = project;
		this.module = module;
		this.submodule = submodule;
		this.featureType = featureType;
		this.name = name;
		this.realUnits = realUnits;
		this.parameters = parameters;
	}

	@Id
	@Column(name = "id_task", unique = true, nullable = false)
	public int getIdTask() {
		return this.idTask;
	}

	public void setIdTask(int idTask) {
		this.idTask = idTask;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_project", nullable = false)
	public Project getProject() {
		return this.project;
	}

	public void setProject(Project project) {
		this.project = project;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_module")
	public Module getModule() {
		return this.module;
	}

	public void setModule(Module module) {
		this.module = module;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_submodule")
	public Submodule getSubmodule() {
		return this.submodule;
	}

	public void setSubmodule(Submodule submodule) {
		this.submodule = submodule;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_feature_type", nullable = false)
	public FeatureType getFeatureType() {
		return this.featureType;
	}

	public void setFeatureType(FeatureType featureType) {
		this.featureType = featureType;
	}

	@Column(name = "name", nullable = false, length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "real_units", nullable = false)
	public int getRealUnits() {
		return this.realUnits;
	}

	public void setRealUnits(int realUnits) {
		this.realUnits = realUnits;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "task_parameters", schema = "public", joinColumns = { @JoinColumn(name = "id_task", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "id_parameter", nullable = false, updatable = false) })
	public Set<Parameter> getParameters() {
		return this.parameters;
	}

	public void setParameters(Set<Parameter> parameters) {
		this.parameters = parameters;
	}

}
