package com.devgear.codesizer.model;

// Generated 24-oct-2011 0:54:57 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TaskParametersHistory generated by hbm2java
 */
@Entity
@Table(name = "task_parameters_history", schema = "public")
public class TaskParametersHistory implements java.io.Serializable {

	private int idTaskParametersHistory;
	private Integer idTask;
	private Integer idParameter;
	private String upUser;
	private Date upDate;

	public TaskParametersHistory() {
	}

	public TaskParametersHistory(int idTaskParametersHistory) {
		this.idTaskParametersHistory = idTaskParametersHistory;
	}

	public TaskParametersHistory(int idTaskParametersHistory, Integer idTask,
			Integer idParameter, String upUser, Date upDate) {
		this.idTaskParametersHistory = idTaskParametersHistory;
		this.idTask = idTask;
		this.idParameter = idParameter;
		this.upUser = upUser;
		this.upDate = upDate;
	}

	@Id
	@Column(name = "id_task_parameters_history", unique = true, nullable = false)
	public int getIdTaskParametersHistory() {
		return this.idTaskParametersHistory;
	}

	public void setIdTaskParametersHistory(int idTaskParametersHistory) {
		this.idTaskParametersHistory = idTaskParametersHistory;
	}

	@Column(name = "id_task")
	public Integer getIdTask() {
		return this.idTask;
	}

	public void setIdTask(Integer idTask) {
		this.idTask = idTask;
	}

	@Column(name = "id_parameter")
	public Integer getIdParameter() {
		return this.idParameter;
	}

	public void setIdParameter(Integer idParameter) {
		this.idParameter = idParameter;
	}

	@Column(name = "up_user", length = 50)
	public String getUpUser() {
		return this.upUser;
	}

	public void setUpUser(String upUser) {
		this.upUser = upUser;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "up_date", length = 29)
	public Date getUpDate() {
		return this.upDate;
	}

	public void setUpDate(Date upDate) {
		this.upDate = upDate;
	}

}
