package com.devgear.codesizer.model;

// Generated 24-oct-2011 0:54:57 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TaskHistory generated by hbm2java
 */
@Entity
@Table(name = "task_history", schema = "public")
public class TaskHistory implements java.io.Serializable {

	private int idTaskHistory;
	private int idTask;
	private Integer idModule;
	private Integer idSubmodule;
	private Integer idFeatureType;
	private int realUnits;
	private String name;
	private String upUser;
	private Date upDate;

	public TaskHistory() {
	}

	public TaskHistory(int idTaskHistory, int idTask, int realUnits, String name) {
		this.idTaskHistory = idTaskHistory;
		this.idTask = idTask;
		this.realUnits = realUnits;
		this.name = name;
	}

	public TaskHistory(int idTaskHistory, int idTask, Integer idModule,
			Integer idSubmodule, Integer idFeatureType, int realUnits,
			String name, String upUser, Date upDate) {
		this.idTaskHistory = idTaskHistory;
		this.idTask = idTask;
		this.idModule = idModule;
		this.idSubmodule = idSubmodule;
		this.idFeatureType = idFeatureType;
		this.realUnits = realUnits;
		this.name = name;
		this.upUser = upUser;
		this.upDate = upDate;
	}

	@Id
	@Column(name = "id_task_history", unique = true, nullable = false)
	public int getIdTaskHistory() {
		return this.idTaskHistory;
	}

	public void setIdTaskHistory(int idTaskHistory) {
		this.idTaskHistory = idTaskHistory;
	}

	@Column(name = "id_task", nullable = false)
	public int getIdTask() {
		return this.idTask;
	}

	public void setIdTask(int idTask) {
		this.idTask = idTask;
	}

	@Column(name = "id_module")
	public Integer getIdModule() {
		return this.idModule;
	}

	public void setIdModule(Integer idModule) {
		this.idModule = idModule;
	}

	@Column(name = "id_submodule")
	public Integer getIdSubmodule() {
		return this.idSubmodule;
	}

	public void setIdSubmodule(Integer idSubmodule) {
		this.idSubmodule = idSubmodule;
	}

	@Column(name = "id_feature_type")
	public Integer getIdFeatureType() {
		return this.idFeatureType;
	}

	public void setIdFeatureType(Integer idFeatureType) {
		this.idFeatureType = idFeatureType;
	}

	@Column(name = "real_units", nullable = false)
	public int getRealUnits() {
		return this.realUnits;
	}

	public void setRealUnits(int realUnits) {
		this.realUnits = realUnits;
	}

	@Column(name = "name", nullable = false, length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "up_user", length = 50)
	public String getUpUser() {
		return this.upUser;
	}

	public void setUpUser(String upUser) {
		this.upUser = upUser;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "up_date", length = 29)
	public Date getUpDate() {
		return this.upDate;
	}

	public void setUpDate(Date upDate) {
		this.upDate = upDate;
	}

}
