package com.devgear.codesizer.core.view;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.terminal.ThemeResource;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.NativeButton;

public class VerticalToolbar extends CustomComponent {

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private NativeButton nativeButton_5;
	@AutoGenerated
	private NativeButton nativeButton_2;
	@AutoGenerated
	private NativeButton nativeButton_1;

	/*- VaadinEditorProperties={"grid":"RegularGrid,5","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public VerticalToolbar() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setIcon(new ThemeResource("../runo/icons/16/folder.png"));
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(false);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// nativeButton_1
		nativeButton_1 = new NativeButton();
		nativeButton_1.setIcon(new ThemeResource(
				"../runo/icons/32/document-image.png"));
		nativeButton_1.setImmediate(true);
		nativeButton_1.setWidth("65px");
		nativeButton_1.setHeight("65px");
		mainLayout.addComponent(nativeButton_1, "top:10.0px;left:10.0px;");
		
		// nativeButton_2
		nativeButton_2 = new NativeButton();
		nativeButton_2.setIcon(new ThemeResource(
				"../runo/icons/32/document-pdf.png"));
		nativeButton_2.setImmediate(true);
		nativeButton_2.setWidth("65px");
		nativeButton_2.setHeight("65px");
		mainLayout.addComponent(nativeButton_2, "top:85.0px;left:10.0px;");
		
		// nativeButton_5
		nativeButton_5 = new NativeButton();
		nativeButton_5.setIcon(new ThemeResource("../runo/icons/32/email.png"));
		nativeButton_5.setImmediate(true);
		nativeButton_5.setWidth("65px");
		nativeButton_5.setHeight("65px");
		mainLayout.addComponent(nativeButton_5, "top:160.0px;left:10.0px;");
		
		return mainLayout;
	}

}
